// Generated by Hassan Portfolio Admin Panel.
// Do not edit manually.
window.PUBLISHED_SITE_DATA = {
  "theme": "emerald-dark",
  "credentials": {
    "username": "admin",
    "password": "Admin@123"
  },
  "site": {
    "name": "Hassan"
  },
  "home": {
    "heroRole": "Virtual Assistant & Data Entry Specialist",
    "heroTagline": "Turning scattered data into organized results, on time, every time.",
    "stats": [
      {
        "value": "800+",
        "label": "Projects completed"
      },
      {
        "value": "6+",
        "label": "Years of experience"
      },
      {
        "value": "2",
        "label": "Fiverr Seller Level"
      },
      {
        "value": "5.0",
        "label": "Average client rating"
      }
    ],
    "ctaHeading": "Ready to get your data organized?",
    "ctaText": "Tell me what you're working with — I'll reply with a clear plan and timeline, usually within a few hours."
  },
  "about": {
    "heroTitle": "From small tasks to 800+ projects.",
    "heroSubtitle": "The short version of how a few local data entry jobs turned into a full-time specialty.",
    "storyIntro": "I started freelancing over 6 years ago, doing small data entry tasks to help local businesses get organized.",
    "storyBody": "Over time I built up deep expertise across data entry, Excel management, transcription, document conversion, and virtual assistance — and turned it into a full-time career supporting businesses, entrepreneurs, and professionals around the world.",
    "missionQuote": "I don't just complete tasks. I bring accuracy, structure, and reliability to messy, disorganized work so my clients can trust the data and focus on growing their business.",
    "storyClose": "What makes me different is the standard I hold my own work to — every spreadsheet, transcript, and document is treated like it needs to be handed straight to a client's boss, investor, or customer, with nothing to double-check. My mission is simple: give clients back their time by handling the administrative details with precision, so they never have to double-check my work."
  },
  "servicesPage": {
    "heroTitle": "Clear services, honest pricing.",
    "heroSubtitle": "Eight ways I help businesses stay organized — each with transparent starting rates and no surprises."
  },
  "portfolioPage": {
    "heroTitle": "A closer look at 800+ projects.",
    "heroSubtitle": "Real work across data entry, document conversion, transcription, and research — organized the way I organize everything else."
  },
  "awardsPage": {
    "heroTitle": "Recognition earned project by project.",
    "heroSubtitle": "A few milestones that reflect the trust clients have placed in the work — not awards for their own sake, but proof of consistency."
  },
  "contact": {
    "heroTitle": "Let's get your data organized.",
    "heroSubtitle": "Reach out for data entry, virtual assistance, transcription, or document conversion projects — I'll reply within a few hours.",
    "email": "hassan3011ali@gmail.com",
    "whatsappText": "Available on request — just ask via the form",
    "responseTime": "Usually within a few hours",
    "fiverrUrl": "https://www.fiverr.com/hassan_30?public_mode=true",
    "linkedinUrl": "https://www.linkedin.com/in/hassan-ali-785b611b7/"
  },
  "images": {
    "profilePhoto": null
  },
  "services": [
    {
      "id": "s1",
      "icon": "grid",
      "title": "Data Entry & Excel Management",
      "description": "Accurate data entry, data cleaning, CRM data entry, and organized Excel spreadsheets built to stay accurate as they grow.",
      "price": "10",
      "unit": "/ hour"
    },
    {
      "id": "s2",
      "icon": "doc",
      "title": "Document & PDF Conversion",
      "description": "Converting PDFs, scanned documents, and images into clean, editable Word or Excel files with formatting preserved.",
      "price": "5",
      "unit": "/ project"
    },
    {
      "id": "s3",
      "icon": "user",
      "title": "Virtual Assistant Services",
      "description": "Ongoing admin support including web research, data collection, email management, and CRM upkeep.",
      "price": "8",
      "unit": "/ hour"
    },
    {
      "id": "s4",
      "icon": "mic",
      "title": "Transcription Services",
      "description": "Accurate audio, video, and podcast transcription with optional timestamps and speaker labeling.",
      "price": "1",
      "unit": "/ audio minute"
    },
    {
      "id": "s5",
      "icon": "search",
      "title": "Web Research & Lead Generation",
      "description": "Building verified contact databases and lead lists from targeted online research, ready for outreach.",
      "price": "15",
      "unit": "/ project"
    },
    {
      "id": "s6",
      "icon": "layers",
      "title": "Business & Brand Naming",
      "description": "Creative, research-backed name suggestions for businesses, products, and brands, with availability checks.",
      "price": "20",
      "unit": "/ package"
    },
    {
      "id": "s7",
      "icon": "design",
      "title": "Logo, Flyer & Graphic Design",
      "description": "Creative design work including logos, flyers, brochures, social media posts, book covers, and resumes — professional visuals tailored to your brand.",
      "price": "15",
      "unit": "/ project"
    },
    {
      "id": "s8",
      "icon": "audio",
      "title": "Audio Editing",
      "description": "Background noise removal, audio enhancement, audio cleaning, and cutting/trimming — clean, polished audio ready to use.",
      "price": "5",
      "unit": "/ audio file"
    }
  ],
  "achievements": [
    {
      "id": "a1",
      "icon": "trophy",
      "title": "Level 2 Seller Status",
      "org": "Fiverr",
      "duration": "Ongoing status",
      "description": "Awarded by Fiverr in recognition of consistent high-quality delivery across 800+ completed projects and strong client satisfaction. It's a standing I've maintained, not a one-time badge — earned through repeat on-time delivery and low revision rates."
    },
    {
      "id": "a2",
      "icon": "handshake",
      "title": "Trusted Long-Term Partner",
      "org": "4 Childcare Centers, New York",
      "duration": "5 years & ongoing",
      "description": "A 5-year and ongoing engagement managing daily attendance and meal-tracking data across CCTA, KidKare, Roster Sheets, and CapsOnline for 4 childcare centers. It reflects the reliability clients depend on for recurring, sensitive administrative work where accuracy directly affects compliance and billing."
    },
    {
      "id": "a3",
      "icon": "archive",
      "title": "Historical Archive Digitization",
      "org": "UK Punjab Heritage Association",
      "duration": "Special project",
      "description": "Selected to manually digitize WWI soldiers' handwritten register records into structured Excel data for the association's website, punjabww1.com — helping preserve historical records and make them accessible to the public and researchers."
    }
  ],
  "projects": [
    {
      "id": "p1",
      "category": "data-entry",
      "title": "WWI Soldier Records Digitization",
      "shortDesc": "Converted handwritten WWI register files into structured Excel data for punjabww1.com.",
      "fullDesc": "Manually converted historical handwritten register files containing WWI soldiers' data into structured, searchable Excel spreadsheets for the UK Punjab Heritage Association's website, punjabww1.com. The work involved carefully transcribing faded and inconsistent handwriting into clean, standardized fields ready for publication and archival use.",
      "image": null
    },
    {
      "id": "p2",
      "category": "data-entry",
      "title": "Childcare Center Attendance & Meal Tracking",
      "shortDesc": "5-year ongoing data entry across CCTA, KidKare, Roster Sheets & CapsOnline for 4 NY daycare centers.",
      "fullDesc": "An ongoing 5-year engagement managing daily attendance and meal-tracking data entry across CCTA, KidKare, Roster Sheets, and CapsOnline systems for 4 daycare centers in New York. Requires consistent daily accuracy across multiple platforms to keep compliance and billing records current.",
      "image": null
    },
    {
      "id": "p3",
      "category": "data-entry",
      "title": "E-Commerce Inventory Spreadsheet System",
      "shortDesc": "Rebuilt a 500+ SKU spreadsheet with formulas, validation, and a live stock dashboard.",
      "fullDesc": "Rebuilt a disorganized 500+ SKU inventory spreadsheet into a structured system with validation rules, reorder formulas, and a live summary dashboard, giving the client daily visibility into stock levels across categories.",
      "image": null
    },
    {
      "id": "p4",
      "category": "document",
      "title": "Scanned Contract Bundle → Editable Word",
      "shortDesc": "120-page scanned PDF converted to editable Word with full formatting preserved.",
      "fullDesc": "Converted a 120-page scanned PDF contract bundle into a fully editable Word document, rebuilding tables, clause numbering, and formatting to match the original layout exactly, so the client's legal team could redline directly.",
      "image": null
    },
    {
      "id": "p5",
      "category": "document",
      "title": "Podcast Episode Transcription Series",
      "shortDesc": "Time-stamped, speaker-labeled transcripts delivered for a 40-episode back catalog.",
      "fullDesc": "Delivered accurate, time-stamped transcripts for a 40-episode podcast back catalog, formatted for both accessibility captions and repurposed blog content, with consistent speaker labeling throughout.",
      "image": null
    },
    {
      "id": "p6",
      "category": "document",
      "title": "Scanned Intake Forms → Fillable PDF",
      "shortDesc": "Paper intake forms rebuilt as fillable, auto-calculating PDF documents.",
      "fullDesc": "Rebuilt a stack of paper client-intake forms as fillable, auto-calculating PDF documents with logical tab order and validation, cutting the client's manual data-entry time significantly.",
      "image": null
    },
    {
      "id": "p7",
      "category": "research",
      "title": "CRM Data Management",
      "shortDesc": "Organized and maintained client records inside Salesforce for an ongoing client.",
      "fullDesc": "Organized and maintained client records inside Salesforce for an ongoing client, standardizing contact fields, deduplicating entries, and keeping pipeline data accurate and current for the sales team.",
      "image": null
    },
    {
      "id": "p8",
      "category": "research",
      "title": "Social Media Account Management",
      "shortDesc": "Managed day-to-day content and posting for a client's Instagram account.",
      "fullDesc": "Managed day-to-day content planning and posting for a client's Instagram account, keeping a consistent posting schedule and brand voice across weekly content.",
      "image": null
    },
    {
      "id": "p9",
      "category": "research",
      "title": "B2B Lead List Research",
      "shortDesc": "Verified 1,000+ B2B decision-maker contacts across six target industries.",
      "fullDesc": "Built a verified list of 1,000+ B2B decision-maker contacts across six target industries, cross-checking company data and role titles for outreach accuracy before handoff to the sales team.",
      "image": null
    },
    {
      "id": "p10",
      "category": "research",
      "title": "Business Naming Package",
      "shortDesc": "A shortlist of distinctive, research-backed name options for a new product launch.",
      "fullDesc": "Delivered a shortlist of distinctive, research-backed name options for a new product launch, including availability checks and a short rationale for each direction.",
      "image": null
    },
    {
      "id": "p11",
      "category": "design",
      "title": "Brand Logo & Flyer Design Package",
      "shortDesc": "Designed a complete logo and promotional flyer set for a small business launch.",
      "fullDesc": "Created a full starter brand identity package for a small business launch — a custom logo in multiple formats, a promotional flyer, and matching social media graphics, delivered print-ready and in editable source files.",
      "image": null
    },
    {
      "id": "p12",
      "category": "design",
      "title": "Podcast Audio Cleanup & Enhancement",
      "shortDesc": "Removed background noise and enhanced audio quality across a client's podcast episodes.",
      "fullDesc": "Cleaned up raw podcast recordings by removing background noise, balancing volume levels, and trimming dead air, delivering polished, ready-to-publish audio files for a client's weekly podcast.",
      "image": "assets/thumb-audio.svg"
    }
  ]
};
